apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data-pvc
  namespace: frigate
  labels:
    app: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-pvc
  namespace: frigate
  labels:
    app: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
